### ISSUE TITLE
Analysis of PDB files

### ISSUE THREAD

**Issue by bcantarel** [flatironinstitute/DeepFRI#15]
I was testing the use of DeepFri on PDB files -- so I downloaded the PDB file for 3LZB from the PDB API
I get the following error:
Traceback (most recent call last):
  File "predict.py", line 41, in <module>
    predictor.predict(args.pdb_fn)
  File "/usr/local/DeepFRI/deepfrier/Predictor.py", line 107, in predict
    A, S, seqres = self._load_cmap(test_prot, cmap_thresh=cmap_thresh)
  File "/usr/local/DeepFRI/deepfrier/Predictor.py", line 74, in _load_cmap
    D, seq = load_predicted_PDB(filename)
  File "/usr/local/DeepFRI/deepfrier/utils.py", line 25, in load_predicted_PDB
    two = residues[y]["CA"].get_coord()
  File "/usr/local/lib/python3.8/dist-packages/Bio/PDB/Entity.py", line 45, in __getitem__
    return self.child_dict[id]
KeyError: 'CA'

I was wondering if that was related to having many chains in the file -- so I tried to split the files into chains using pdb-tools (pub_splitchain) and I got a similar error:
/usr/local/lib/python3.8/dist-packages/Bio/SeqIO/PdbIO.py:303: BiopythonParserWarning: 'HEADER' line not found; can
't determine PDB ID.
  warnings.warn(
Traceback (most recent call last):
  File "predict.py", line 41, in <module>
    predictor.predict(args.pdb_fn)
  File "/usr/local/DeepFRI/deepfrier/Predictor.py", line 107, in predict
    A, S, seqres = self._load_cmap(test_prot, cmap_thresh=cmap_thresh)
  File "/usr/local/DeepFRI/deepfrier/Predictor.py", line 74, in _load_cmap
    D, seq = load_predicted_PDB(filename)
  File "/usr/local/DeepFRI/deepfrier/utils.py", line 25, in load_predicted_PDB
    two = residues[y]["CA"].get_coord()
  File "/usr/local/lib/python3.8/dist-packages/Bio/PDB/Entity.py", line 45, in __getitem__
    return self.child_dict[id]
KeyError: 'CA'

I'm not quite sure if there is another preferred input file.

**Comment by PawelSzczerbiak** [comment]
Sorry for late answer - this is a common problem in DeepFRI. As a workaround you can remove all residues without `CA` atom flag. However, the best way to run DeepFRI is to use contact maps generated e.g. from `.cif` files.
