### ISSUE TITLE
SavedModel file does not exist

### ISSUE THREAD

**Issue by francicco** [flatironinstitute/DeepFRI#42]
Hi,

I was trying to test your software.

I tried your command line for fasta file:

`python predict.py --fasta_fn examples/pdb_chains.fasta -ont mf -v`

But I got this?

```
2023-09-29 12:57:17.302713: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "predict.py", line 40, in <module>
    predictor = Predictor(models[ont], gcn=gcn)
  File "/user/work/tk19812/software/DeepFRI-1.0.0/deepfrier/Predictor.py", line 53, in __init__
    self._load_model()
  File "/user/work/tk19812/software/DeepFRI-1.0.0/deepfrier/Predictor.py", line 56, in _load_model
    self.model = tf.keras.models.load_model(self.model_prefix + '.hdf5',
  File "/user/work/tk19812/software/DeepFRI-1.0.0/venv/lib/python3.8/site-packages/tensorflow/python/keras/saving/save.py", line 186, in load_model
    loader_impl.parse_saved_model(filepath)
  File "/user/work/tk19812/software/DeepFRI-1.0.0/venv/lib/python3.8/site-packages/tensorflow/python/saved_model/loader_impl.py", line 110, in parse_saved_model
    raise IOError("SavedModel file does not exist at: %s/{%s|%s}" %
OSError: SavedModel file does not exist at: ./trained_models/DeepCNN-MERGED_molecular_function.hdf5/{saved_model.pbtxt|saved_model.pb}
```

Any help?
F

**Comment by xiha-haxi** [comment]
you could download the trained_models from the bottom of readme. Then unzip it and get it.

**Comment by song2000012138** [comment]
the link 'https://cdn.rcsb.org/resources/sequence/clusters/bc-95.out' in data_collection.sh can't work ,can you give me some guidance?

**Comment by song2000012138** [comment]
> you could download the trained_models from the bottom of readme. Then unzip it and get it.

the link 'https://cdn.rcsb.org/resources/sequence/clusters/bc-95.out' in data_collection.sh can't work ,can you give me some guidance?
